#!/bin/bash
git pull
echo "# Myconfigs" > README.md
for i in {".i3",".vimrc",".Xdefaults",".xmobarrc",".Xmodmap",".zshrc",".config/nvim"};
do 
	rm -rf codes/home/alex/$i;
	cp -rf {~,codes/home/alex}/$i;
done
git init
git add .
git commit -m "first commit"
git remote add origin https://github.com/Alex-Tsvetanov/myconfigs.git
git push -u origin master
######################                   .config
######################                   .i3
######################                   .vimrc
######################                   .Xauthority
######################                   .Xdefaults
######################                   .xmobarrc
######################                   .Xmodmap
######################                   .xmonad
######################                   .Xresources
######################                   .zshrc

