#!/bin/bash
i3status | while :
do
    read line
    LG=$(xset -q|grep LED| awk '{ print $10 }')
    if [ $LG == "00001004" ]
    then
        dat="[{ \"full_text\": \"LANG: BG\", \"color\":\"#00FF00\" },"
    else
        if [ $LG == "00000000" ]
        then
            dat="[{ \"full_text\": \"LANG: EN\", \"color\":\"#0000FF\" },"
        fi
    fi
    echo "${line/[/$dat}" || exit 1
done
